return {
  hint = '',
  info = '',
  warn = '',
  error = '',
  modified = '', -- 󰅸 * 
  readonly = '󰌾',
  unnamed = '',
  newfile = '',
  search = '', --  
  lsp_completion = {
    Text = '',
    Method = '',
    Function = '',
    Constructor = '',
    Field = '',
    Variable = '',
    Class = 'ﴯ',
    Interface = '',
    Module = '',
    Property = 'ﰠ',
    Unit = '',
    Value = '',
    Enum = '',
    Keyword = '',
    Snippet = '',
    Color = '',
    File = '',
    Reference = '',
    Folder = '',
    EnumMember = '',
    Constant = '',
    Struct = '',
    Event = '',
    Operator = '',
    TypeParameter = '',
    Tab9 = '',
    Codeium = '{…}', -- 󰞔 →
  },
  ai = {
    Chat = '', --     
    Test = '', --    
    Regex = '', --   
    Comment = '', --  
    Code = '', --   
    Text = '', --   
    Items = '', --    
    Swap = '', -- 
    Keep = '', --  
    into = '', --  
  }
}
