#!/usr/bin/env sh

# Modified Nightfox master Palette
COLOR_BLACK=0xdd242220
COLOR_DARK=0xaa242220
COLOR_WHITE=0xccfdf9f9
COLOR_LIGHT=0x88fdf9f9
COLOR_GREEN=0xff97b87b
COLOR_YELLOW=0xffe0bb70
COLOR_ORANGE=0xffc98b65
COLOR_RED=0xffbf5454
COLOR_PURPLE=0xffCC9EFF

# Color tokens
SKBAR_COLOR_ICON=$COLOR_WHITE
SKBAR_COLOR_LABEL_ACTIVE=$COLOR_WHITE
SKBAR_COLOR_LABEL=$COLOR_LIGHT

# Bar
HEIGHT=34
PADDING=0
BLUR=25

# Popup
POPUP_BORDER_WIDTH=1
POPUP_CORNER_RADIUS=8
POPUP_OFFSET=-5
POPUP_COLOR_BG=$COLOR_BLACK
POPUP_COLOR_BORDER=$COLOR_WHITE

# Label
LABEL_PADDING=5
LABEL_PADDING_L=2
LABEL_PADDING_R=6
SPACER_PADDING=12
FONT="SF Pro:Semibold"
LABEL_OFFSET=-4
LABEL_SUP_OFFSET=6
LABEL_SIZE=11.0
LABEL_SUP_SIZE=7.0
LABEL_SUB_SIZE=8.0
LABEL_MUSIC_SIZE=9.0

# Icon
ICON_PADDING=2
ICON_PADDING_L=6
ICON_PADDING_R=2
ICON_FONT="Hack Nerd Font:Regular"
ICON_FONT_ALT="Font Awesome 7 Brands:Regular"
ICON_SIZE=12.0
ICON_SIZE_XL=14.0

# Timing
POLL_UPDATES=5
POLL_UPDATES_MID=25
POLL_UPDATES_LONG=1500
POLL_UPDATES_DAILY=21600

# Other
SK_FONT="sketchybar-app-font:Regular"
SPACE_HEIGHT=1
SPACE_BG_OFFSET=-10
CORNER_RADIUS=5
BORDER_WIDTH=1
SHADOW=on
ITEMS="$CONFIG_DIR/items"
